### ISSUE TITLE
General development discussion

### ISSUE THREAD

**Issue by inflex** [inflex/OpenBoardView#19]
While I'm waiting for the cross platform base to be formalised,  I've still gone ahead with feature developments on this fork which at this point does build both in linux and windows (under VS2015).

At the time of starting this thread, the following features have been included;

- FZ, BRD, BRV support (FZ needs a key added in FZfile.h, I cannot provide that key)
- Recently used file history
- Support for WASD/X,  numpad-arrows, Inverted-T arrows keyboard control
- No textures required (all vector generated)
- Proper angled part representation
- Connectors better represented 
- Slow CPU support (drops AA and cuts off rendering of pins below a size threshold)
- Component search with up to three (3) items
- Configuration file support
- Command line parameters (Linux)
- Visual mask-out of non-relevant pins when a pin/network is selected

As always, there's plenty more things to add.  Most of the items added are done so because I find them useful / wanted when I'm using OBV for my own repair work.

It should be noted that I am using it on Ubuntu 16.04 (for now),  Pentium G3420 (3.2GHz) and standard Intel GFX and dual 1920x1200 LCD.

**Comment by inflex** [comment]
With the new 3 column component search, you can TAB between the 3 fields. Soon as you click on a part it'll assign that part code to that field.  

Down the bottom you can commit to the Search (Return/Enter), or Reset the fields, or Exit (ESC) outright.

![ss](https://cloud.githubusercontent.com/assets/5660591/16898989/17a2b9cc-4c36-11e6-84c5-40df3c67324e.png)

**Comment by inflex** [comment]
Showing the selectedMask effect on the board rendering when you've selected a pin/net.

Because the mask is a full RGBA quad there's nothing stopping you masking out other colour channels as well ( not just the alpha ).

![ss](https://cloud.githubusercontent.com/assets/5660591/16899007/a4412c92-4c36-11e6-9b34-aa96a3edcbdc.png)

**Comment by inflex** [comment]
After using it a bit more I decided to break the masking in to three separate units, so that each one applies uniquely to the board render part (pins, part outlines, board outline ).

selectedMaskPins		=	0xffffff4f
selectedMaskParts		=	0xffffff8f
selectedMaskOutline	=	0xffffff8f

**Comment by inflex** [comment]
On the linux version, after talking with @piernov , we've changed the idle-detection around a bit, so hopefully that'll improve the non-active CPU consumption for a few people.

**Comment by inflex** [comment]
Fast approaching my own personal v1.00 release point.

Have the dpi sorted out, board fill is good, annotations are working, and a reasonable level of board formats now supported ( though I need to formalise the bv -> bvr conversion )

With all the features turned on I'm still getting 60fps on 1440x900 with the K90 and A1502 board renders on the dual-celeron with integrated graphics.

![ss](https://cloud.githubusercontent.com/assets/5660591/17322415/b6029ce8-58e0-11e6-9eac-478919940637.png)

**Comment by piernov** [comment]
A few questions which come up after my latest work, not so important but still want to know what do you think:

1. Now that it builds for Windows with `main_opengl.cpp` and we have an OpenGL 1.1 renderer, should we consider dropping support for DirectX 9?
2. Also, since the CMake scripts now handle the building for OS X, should we drop the XCode project?
3. Should we drop the VS project when everything will be finished up with building for Win32 using CMake?
4. Should we continue to embed the `FiraSans-Medium.ttf` font in the Windows build (which is still the default)? Or allow the user to specify an external font?

**Comment by inflex** [comment]
I'm a bit out of my depth with a couple here, so I'll answer with probably more questions ;)

1: I'm fine to drop DX9 assuming it doesn't break anything ?

2: Would make sense, unless you can conjure a reason for keeping the XCode?

3: Perhaps keep the VS Project to one side as an alternative option / reference for ppl who might want to use VS - that said, my own VS2015 project file is now quite different to the one contained in the git repo

4:  I've wondered about this, I'd personally rather not embedding the font.  What's the risk if we leave it out?  What font will it fall back to (ImGui has its own internal font doesn't it?)

**Comment by piernov** [comment]
1. OpenGL renderer on Windows needs more testing and not everything is working as it should. After that, would be ok to remove Dx9.
2. Currently no reason, the CMake build does nearly the same thing as XCode, without us having to update and build manually the XCode project (and it has been broken for some time).
3. Yep, I'm sorry for not updating the VS project in my changes. Probably easier for people to fire up Visual Studio and hit the Build button rather than figure out how to generate things with CMake. The only drawback is we need to keep it updated and that requires having a Visual Studio installation.
4. The default ImGui font is a bit too small compared to the one we use and doesn't handle Unicode well I think. Not really an issue but having an embedded font makes thing easier for the user. Now I still don't like embedding assets, the only drawback is that the user would have to carry around the font with the executable; ie. same as on Linux right now where the binary loads the font from the asset/ folder.

**Comment by piernov** [comment]
1. I think everything is now working on the cross-compiled Win32 OpenGL build. We should still keep the Dx9 build in case for now.
2. OS X build using CMake still works without any issue and the XCode project is probably completely broken. Should now be removed.
3. As the Dx9 build uses the VS project, it should be kept until we completely delete the support for this build.
4. All build now use system font and the embedded fonts were removed.

**Comment by inflex** [comment]
Agreed, doesn't hurt to keep some of the existing build items in there for now; they're not inhibiting at this stage.
