### ISSUE TITLE
Split file board format (ASC)

### ISSUE THREAD

**Issue by inflex** [inflex/OpenBoardView#43]
Was attempting to repair a laptop mainboard today, in this case an ASUS X550CC, and the boardview that I could find for it (as opposed to X550VC) was unfortunately a split-file package, that is, each aspect of the board is defined in a separate file (format, pins, nails, parts, nets).

These are all contained within a single folder, so probably we can load them up that way, else load a single item and then we note that we have to load all the other possible parts.

The *other* option is to create an external converter so we can do a single operation to convert all files in to an alternative format (perhaps the BVR[aw]) format?)

[X550CCR2.zip](https://github.com/inflex/OpenBoardView/files/416996/X550CCR2.zip)

**Comment by piernov** [comment]
Basic support for *.asc is implemented on my `feat/asc-support` branch. Only supports loading `format.asc`, `pins.asc` and `nails.asc` (but I'm pretty sure that last one isn't parsed correctly), ie. what's supported in the .bdv format. You can select either one of the *.asc file or the .bom file to load the boardview, it'll load automatically those 3 files from the same directory.
There may be some useful informations in the `.bom` file or `parts.asc` and `nets.asc` so it may be interesting to add support in the future.
Also the `.bdv` parser should make use of the functions in `ASCFile.cpp` because the format/parts/pins/nails parser is the same.

Attached is another boardview with a `.bom` file.
[Asus F5V, r1.1.zip](https://github.com/inflex/OpenBoardView/files/454028/Asus.F5V.r1.1.zip)

**Comment by inflex** [comment]
Thanks @piernov .

Had to add in a Mirror() feature because the board I was loading is mirrored but it's nothing to do with the decoding of the fileformat, it's just likely that they referenced it to another orientation.   Good to have it regardless.

The ASC decoder seems to work nice,  very compact too :+1:
